// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBypyk4naTPFpdOXMF-VakFJwHWU3_ssVI',
    appId: '1:705187779457:web:9c8b6a821cfd1ea7d50e80',
    messagingSenderId: '705187779457',
    projectId: 'cookbook-27d6c',
    authDomain: 'cookbook-27d6c.firebaseapp.com',
    storageBucket: 'cookbook-27d6c.firebasestorage.app',
    measurementId: 'G-EE31ZGYWR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxW_sxNEUgIDz5rLUcSfS4P9DFCPIlMVk',
    appId: '1:705187779457:android:192c982bbdc16179d50e80',
    messagingSenderId: '705187779457',
    projectId: 'cookbook-27d6c',
    storageBucket: 'cookbook-27d6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlHsZF7c6IiJ6VCGgLgyM3ZtVvAzWlTA',
    appId: '1:705187779457:ios:af3d60337f1f223bd50e80',
    messagingSenderId: '705187779457',
    projectId: 'cookbook-27d6c',
    storageBucket: 'cookbook-27d6c.firebasestorage.app',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlHsZF7c6IiJ6VCGgLgyM3ZtVvAzWlTA',
    appId: '1:705187779457:ios:af3d60337f1f223bd50e80',
    messagingSenderId: '705187779457',
    projectId: 'cookbook-27d6c',
    storageBucket: 'cookbook-27d6c.firebasestorage.app',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBypyk4naTPFpdOXMF-VakFJwHWU3_ssVI',
    appId: '1:705187779457:web:2dde9aa9f17ed58cd50e80',
    messagingSenderId: '705187779457',
    projectId: 'cookbook-27d6c',
    authDomain: 'cookbook-27d6c.firebaseapp.com',
    storageBucket: 'cookbook-27d6c.firebasestorage.app',
    measurementId: 'G-G0YX3LT9VB',
  );
}
